In [1]:
import numpy as np
import pandas as pd

### Pandas

Загрузим данные:

In [2]:
df = pd.read_csv('DataAnalyst.csv')

Посмотрим на них:

In [3]:
df.head()

Unnamed: 0                                          Job Title  \
0           0  Data Analyst, Center on Immigration and Justic...   
1           1                               Quality Data Analyst   
2           2  Senior Data Analyst, Insights & Analytics Team...   
3           3                                       Data Analyst   
4           4                             Reporting Data Analyst   

              Salary Estimate  \
0  $37K-$66K (Glassdoor est.)   
1  $37K-$66K (Glassdoor est.)   
2  $37K-$66K (Glassdoor est.)   
3  $37K-$66K (Glassdoor est.)   
4  $37K-$66K (Glassdoor est.)   

                                     Job Description  Rating  \
0  Are you eager to roll up your sleeves and harn...     3.2   
1  Overview\n\nProvides analytical and technical ...     3.8   
2  We’re looking for a Senior Data Analyst who ha...     3.4   
3  Requisition NumberRR-0001939\nRemote:Yes\nWe c...     4.1   
4  ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...     3.9   

                              Company Name      Location  Headquarters  \
0           Vera Institute of Justice\n3.2  New York, NY  New York, NY   
1  Visiting Nurse Service of New York\n3.8  New York, NY  New York, NY   
2                         Squarespace\n3.4  New York, NY  New York, NY   
3                            Celerity\n4.1  New York, NY    McLean, VA   
4                             FanDuel\n3.9  New York, NY  New York, NY   

                     Size  Founded               Type of ownership  \
0    201 to 500 employees     1961          Nonprofit Organization   
1        10000+ employees     1893          Nonprofit Organization   
2  1001 to 5000 employees     2003               Company - Private   
3    201 to 500 employees     2002  Subsidiary or Business Segment   
4   501 to 1000 employees     2009               Company - Private   

                           Industry                            Sector  \
0                 Social Assistance                        Non-Profit   
1  Health Care Services & Hospitals                       Health Care   
2                          Internet            Information Technology   
3                       IT Services            Information Technology   
4               Sports & Recreation  Arts, Entertainment & Recreation   

                      Revenue Competitors Easy Apply  
0  $100 to $500 million (USD)          -1       True  
1      $2 to $5 billion (USD)          -1         -1  
2    Unknown / Non-Applicable     GoDaddy         -1  
3   $50 to $100 million (USD)          -1         -1  
4  $100 to $500 million (USD)  DraftKings       True

In [4]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2253 entries, 0 to 2252
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         2253 non-null   int64  
 1   Job Title          2253 non-null   object 
 2   Salary Estimate    2253 non-null   object 
 3   Job Description    2253 non-null   object 
 4   Rating             2253 non-null   float64
 5   Company Name       2252 non-null   object 
 6   Location           2253 non-null   object 
 7   Headquarters       2253 non-null   object 
 8   Size               2253 non-null   object 
 9   Founded            2253 non-null   int64  
 10  Type of ownership  2253 non-null   object 
 11  Industry           2253 non-null   object 
 12  Sector             2253 non-null   object 
 13  Revenue            2253 non-null   object 
 14  Competitors        2253 non-null   object 
 15  Easy Apply         2253 non-null   object 
dtypes: float64(1), int64(2),

In [5]:
# Определим количество строк и столбцов в датафрейме
rows_count = df.shape[0]
cols_count = df.shape[1]
'У нас %s строк и %s колонок.' % (rows_count, cols_count)

'У нас 2253 строк и 16 колонок.'

In [6]:
# Посмотрим, в каких столбцах есть пропуски
df.isnull().sum()

Unnamed: 0           0
Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         1
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
Easy Apply           0
dtype: int64

Видим, что в колонке ```Company Name``` есть пропуск.

In [7]:
df.columns

Index(['Unnamed: 0', 'Job Title', 'Salary Estimate', 'Job Description',
       'Rating', 'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'Easy Apply'],
      dtype='object')

Удалим нулевую колонку.

In [8]:
df = df.drop(df.columns[[0]], axis=1)

In [9]:
df.head()

Job Title  \
0  Data Analyst, Center on Immigration and Justic...   
1                               Quality Data Analyst   
2  Senior Data Analyst, Insights & Analytics Team...   
3                                       Data Analyst   
4                             Reporting Data Analyst   

              Salary Estimate  \
0  $37K-$66K (Glassdoor est.)   
1  $37K-$66K (Glassdoor est.)   
2  $37K-$66K (Glassdoor est.)   
3  $37K-$66K (Glassdoor est.)   
4  $37K-$66K (Glassdoor est.)   

                                     Job Description  Rating  \
0  Are you eager to roll up your sleeves and harn...     3.2   
1  Overview\n\nProvides analytical and technical ...     3.8   
2  We’re looking for a Senior Data Analyst who ha...     3.4   
3  Requisition NumberRR-0001939\nRemote:Yes\nWe c...     4.1   
4  ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...     3.9   

                              Company Name      Location  Headquarters  \
0           Vera Institute of Justice\n3.2  New York, NY  New York, NY   
1  Visiting Nurse Service of New York\n3.8  New York, NY  New York, NY   
2                         Squarespace\n3.4  New York, NY  New York, NY   
3                            Celerity\n4.1  New York, NY    McLean, VA   
4                             FanDuel\n3.9  New York, NY  New York, NY   

                     Size  Founded               Type of ownership  \
0    201 to 500 employees     1961          Nonprofit Organization   
1        10000+ employees     1893          Nonprofit Organization   
2  1001 to 5000 employees     2003               Company - Private   
3    201 to 500 employees     2002  Subsidiary or Business Segment   
4   501 to 1000 employees     2009               Company - Private   

                           Industry                            Sector  \
0                 Social Assistance                        Non-Profit   
1  Health Care Services & Hospitals                       Health Care   
2                          Internet            Information Technology   
3                       IT Services            Information Technology   
4               Sports & Recreation  Arts, Entertainment & Recreation   

                      Revenue Competitors Easy Apply  
0  $100 to $500 million (USD)          -1       True  
1      $2 to $5 billion (USD)          -1         -1  
2    Unknown / Non-Applicable     GoDaddy         -1  
3   $50 to $100 million (USD)          -1         -1  
4  $100 to $500 million (USD)  DraftKings       True

In [10]:
df.duplicated().sum()

0

In [11]:
df['Easy Apply'].value_counts()

-1      2173
True      80
Name: Easy Apply, dtype: int64

In [12]:
df['Size'].value_counts()

51 to 200 employees        421
10000+ employees           375
1001 to 5000 employees     348
1 to 50 employees          347
201 to 500 employees       249
501 to 1000 employees      211
-1                         163
5001 to 10000 employees     97
Unknown                     42
Name: Size, dtype: int64

In [13]:
nan_list = [-1, -1.0, '-1']
df.replace(nan_list, np.nan, inplace=True)

In [14]:
df.isnull().sum()

Job Title               0
Salary Estimate         1
Job Description         0
Rating                272
Company Name            1
Location                0
Headquarters          172
Size                  163
Founded               660
Type of ownership     163
Industry              353
Sector                353
Revenue               163
Competitors          1732
Easy Apply           2173
dtype: int64

Видим, что в таблице очень много пропусков.

In [15]:
df['Company Name'], _ = df['Company Name'].str.split('\n', 1).str
df['Job Title'], df['Department'] = df['Job Title'].str.split(',', 1).str
df['Salary Estimate'], _ = df['Salary Estimate'].str.split('(', 1).str

C:\Users\userpc\AppData\Local\Temp\ipykernel_1896\1058043015.py:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df['Company Name'], _ = df['Company Name'].str.split('\n', 1).str
C:\Users\userpc\AppData\Local\Temp\ipykernel_1896\1058043015.py:2: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df['Job Title'], df['Department'] = df['Job Title'].str.split(',', 1).str
C:\Users\userpc\AppData\Local\Temp\ipykernel_1896\1058043015.py:3: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df['Salary Estimate'], _ = df['Salary Estimate'].str.split('(', 1).str


In [16]:
df['Salary_min'], df['Salary_max'] = df['Salary Estimate'].str.split('-').str
df['Salary_min'] = df['Salary_min'].str.strip(' ').str.lstrip('$').str.rstrip('K').fillna(0).astype('int')
df['Salary_max'] = df['Salary_max'].str.strip(' ').str.lstrip('$').str.rstrip('K').fillna(0).astype('int')
df.drop(['Salary Estimate'], axis=1, inplace=True)

C:\Users\userpc\AppData\Local\Temp\ipykernel_1896\1928536119.py:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df['Salary_min'], df['Salary_max'] = df['Salary Estimate'].str.split('-').str


In [17]:
df.head()

Job Title                                    Job Description  \
0            Data Analyst  Are you eager to roll up your sleeves and harn...   
1    Quality Data Analyst  Overview\n\nProvides analytical and technical ...   
2     Senior Data Analyst  We’re looking for a Senior Data Analyst who ha...   
3            Data Analyst  Requisition NumberRR-0001939\nRemote:Yes\nWe c...   
4  Reporting Data Analyst  ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...   

   Rating                        Company Name      Location  Headquarters  \
0     3.2           Vera Institute of Justice  New York, NY  New York, NY   
1     3.8  Visiting Nurse Service of New York  New York, NY  New York, NY   
2     3.4                         Squarespace  New York, NY  New York, NY   
3     4.1                            Celerity  New York, NY    McLean, VA   
4     3.9                             FanDuel  New York, NY  New York, NY   

                     Size  Founded               Type of ownership  \
0    201 to 500 employees   1961.0          Nonprofit Organization   
1        10000+ employees   1893.0          Nonprofit Organization   
2  1001 to 5000 employees   2003.0               Company - Private   
3    201 to 500 employees   2002.0  Subsidiary or Business Segment   
4   501 to 1000 employees   2009.0               Company - Private   

                           Industry                            Sector  \
0                 Social Assistance                        Non-Profit   
1  Health Care Services & Hospitals                       Health Care   
2                          Internet            Information Technology   
3                       IT Services            Information Technology   
4               Sports & Recreation  Arts, Entertainment & Recreation   

                      Revenue Competitors Easy Apply  \
0  $100 to $500 million (USD)         NaN       True   
1      $2 to $5 billion (USD)         NaN        NaN   
2    Unknown / Non-Applicable     GoDaddy        NaN   
3   $50 to $100 million (USD)         NaN        NaN   
4  $100 to $500 million (USD)  DraftKings       True   

                                         Department  Salary_min  Salary_max  
0           Center on Immigration and Justice (CIJ)          37          66  
1                                               NaN          37          66  
2   Insights & Analytics Team [Customer Operations]          37          66  
3                                               NaN          37          66  
4                                               NaN          37          66

In [18]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2253 entries, 0 to 2252
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Job Title          2253 non-null   object 
 1   Job Description    2253 non-null   object 
 2   Rating             1981 non-null   float64
 3   Company Name       2252 non-null   object 
 4   Location           2253 non-null   object 
 5   Headquarters       2081 non-null   object 
 6   Size               2090 non-null   object 
 7   Founded            1593 non-null   float64
 8   Type of ownership  2090 non-null   object 
 9   Industry           1900 non-null   object 
 10  Sector             1900 non-null   object 
 11  Revenue            2090 non-null   object 
 12  Competitors        521 non-null    object 
 13  Easy Apply         80 non-null     object 
 14  Department         230 non-null    object 
 15  Salary_min         2253 non-null   int32  
 16  Salary_max         2253 

Посмотрим на уникальные в колонках.

In [19]:
unique_counts = pd.DataFrame.from_records([(col, df[col].nunique()) for col in df.columns],
                                          columns=['Column_Name', 'Num_Unique']).sort_values(by=['Num_Unique'])

In [20]:
unique_counts

Column_Name  Num_Unique
13         Easy Apply           1
6                Size           8
11            Revenue          13
8   Type of ownership          14
10             Sector          24
2              Rating          36
15         Salary_min          53
16         Salary_max          60
9            Industry          88
7             Founded         160
14         Department         186
4            Location         253
12        Competitors         290
5        Headquarters         482
0           Job Title        1167
3        Company Name        1501
1     Job Description        2253

Потом по этой таблице определим категориальные значения, а пока

<center>
<img src="https://cs5.pikabu.ru/post_img/2015/12/04/5/1449210847155432089.jpg"/>

### Numpy

1. Вычислите A + B, A - B

 $\\
A = \left(
\begin{array}{cccc}
1 & -2 & 4\\
2 & 0 & -1\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
5 & 2 & 3\\
4 & 6 & 2\\
\end{array}
\right)$

In [21]:
A = np.array([[1, -2, 4], [2, 0, -1]])
B = np.array([[5, 2, 3], [4, 6, 2]])

In [22]:
A + B, A - B

(array([[6, 0, 7],
        [6, 6, 1]]),
 array([[-4, -4,  1],
        [-2, -6, -3]]))

2. Найдите матрицу С = A - 3B

 $\\
A = \left(
\begin{array}{cccc}
1 & 2 \\
2 & -1\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
-1 & 1 \\
1 & 2\\
0 & 0\\
\end{array}
\right)$

In [23]:
A = np.array([[1, 2], [2, -1], [3, 0]])
B = np.array([[-1, 1], [1, 2], [0, 0]])

In [24]:
A - 3 * B

array([[ 4, -1],
       [-1, -7],
       [ 3,  0]])

3. Вычислите С = AB

 $\\
A = \left(
\begin{array}{cccc}
1 & -1 \\
2 & 0\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
1 & 1 \\
2 & 0\\
\end{array}
\right)$

In [25]:
A = np.array([[1, -1], [2, 0], [3, 0]])
B = np.array([[1, 1], [2, 0]])

In [26]:
A @ B

array([[-1,  1],
       [ 2,  2],
       [ 3,  3]])

4. Вычислите определитель матрицы А

 $\\
A = \left(
\begin{array}{cccc}
6 & -1 & 4\\
2 & 1 & 10\\
8 & 0 & 2\\
\end{array}
\right)$

In [27]:
A = np.array([[6, -1, 4], [2, 1, 10], [8, 0, 2]])
np.linalg.det(A)

-95.99999999999999

5. Вычислите матрицу, обратную матрице А. И покажите, что она действительно является обратной

 $\\
A = \left(
\begin{array}{cccc}
3 & 3 & -1\\
4 & 1 & 3\\
1 & -2 & -2\\
\end{array}
\right)$

In [28]:
A_ = np.array([[3, 3, -1], [4, 1, 3], [1, -2, -2]])

A_inv = np.linalg.inv(A_)
A_inv

array([[ 0.07407407,  0.14814815,  0.18518519],
       [ 0.2037037 , -0.09259259, -0.24074074],
       [-0.16666667,  0.16666667, -0.16666667]])

Проверяем полученный результат:

In [29]:
a = A_inv @ A_
np.rint(a)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [-0., -0.,  1.]])

In [30]:
b = A_ @ A_inv
np.rint(b)

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [-0.,  0.,  1.]])

In [31]:
np.rint(a) == np.rint(b)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Равенство выполняется, следовательно, обратная матрица найдена верно.
